[package]
name = "anathema-widgets"
version.workspace = true
edition.workspace = true

[dependencies]
anathema-debug = { path = "../anathema-debug" }
anathema-geometry = { path = "../anathema-geometry" }
anathema-state = { path = "../anathema-state" }
anathema-store = { path = "../anathema-store" }
anathema-templates = { path = "../anathema-templates" }
flume = { workspace = true }
unicode-width = { workspace = true }
unicode-segmentation = "1.11.0"

[lints]
workspace = true
